### ISSUE TITLE
To be able to click on dependencies of a project

### ISSUE THREAD

**Issue by philibe** [pmsipilot/pmsiplan#30]
Quand on est sur une ligne de version d'un projet, sont affichées la ou les dépendances associées trouvées grâce à la version de release générale . ça serait bien de pouvoir cliquer dessus, pour avoir l'autre projet dépendant, voire la version associée du projet dépendant.

**Comment by wixyvir** [comment]
:hear_no_evil: Je n'ai pas compris

Close ?

**Comment by philibe** [comment]
salut :)

De mémoire il y a pas ou peu de liens entre les dépendances. Il faut aller les chercher à la mains.
