### ISSUE TITLE
Removing project type ?

### ISSUE THREAD

**Issue by willgarcia** [pmsipilot/pmsiplan#35]
Actually this information is too specific (and hard-coded: `hosp|core`) and doesn't help the user. Anyone interested to keep it ?

**Comment by youknowriad** [comment]
+1

**Comment by youknowriad** [comment]
I think a release type is better, and it must be dynamic, it will allow us to say it's BI release or PMSI release

**Comment by jubianchi** [comment]
:+1: the types list should be customizable.

**Comment by wixyvir** [comment]
We'll see what to do after #42 is closed
